### ISSUE TITLE
Подумать, как это может выглядеть на часах.

### ISSUE THREAD

**Issue by egv** [8ofproject/2ch-Browser-iOS#107]
Очевидно, что для часов нужно какое-то свое, особое представление данных, потому что читать посты с них как-то адовато.

Пока идеи крутятся вокруг нотификации на тему упоминаний / ответов в тредах и / или появления новых тредов / постов с ключевыми словами.

Хотя, с русским голосовым вводом можно вполне себе нормально даже и постить.

@8ofproject какие мысли?

**Comment by 8ofproject** [comment]
@egv Быстрый ответ как вариант (если с пасскодом, чтобы отправка без капчи была) - но тут тогда нужно всё же сообщение показывать (иначе не понятно будет на что отвечать). Плохо, что часы не умеют запускать приложения - было бы удобно. Один новый ответ - жмёшь - открывается сразу нужный тред на телефоне. Но увы.
Думаю, пока стоит остановится с отправкой на часы новых сообщений в темах, которые помечены на слежение (они будут в боковом меню, которое...будет :trollface: ).
К боковому меню всё сейчас и идёт - все обновления, которые не исправления ошибок - там будут всякие отслеживаемые треды, оттуда и для часов можно будет брать.

**Comment by egv** [comment]
Ну на часах есть hand off, то есть если ты читаешь письмо на них, то на и фоне его можно будет открыть для ответа. Это имеет api, можно сделать и здесь
