### ISSUE TITLE
Встроить хранение посещённых тредов

### ISSUE THREAD

**Issue by 8ofproject** [8ofproject/2ch-Browser-iOS#145]
Пока не понятно где всё это хранить - в памяти или на диске. Сначала надо разобраться в причине падений при 100+ сообщений в треде. Лично с таким багом не сталкивался.

**Comment by 8ofproject** [comment]
Похоже что проблема падений в iOS 7.0. Тестировать не на чем.

**Comment by egv** [comment]
Дропни поддержку 7 и всё. Что-то мне подсказывает, что в сентябре её и без нас дропнут.

**Comment by 8ofproject** [comment]
@egv Хороший идея! Дропнул пока поддержку 7.0.
На 7.1 очень шустро всё идёт после оптимизаций.
