### ISSUE TITLE
Исправить порядок сортировки разделов

### ISSUE THREAD

**Issue by alextewpin** [8ofproject/2ch-Browser-iOS#16]
Должен быть как в десктопной версии:
Тематика
Творчество
Техника и софт
Игры
Японская культура
Разное
Взрослым
Политика
Пробное
Пользовательские

**Comment by 8ofproject** [comment]
Про разделы интересная история.
Скажем, по умолчанию мы не будем показывать раздел **Взрослым** (по очевидным причинам).
Пользователь по тапу на "+" добавляет какую-то из досок этого раздела. Что происходит при этом? Ведь явно не в избранное должно идти, пользователю может оно в избранном и не нужно.

Должно идти сразу в свою категорию (но категории нет, и до асинхронного подхвата с сервера мы её не узнаем (это продолжение разговора в e-mail - напоминаю, ты предложил добавлять адрес доски сразу, а название потом подхватывать). Как быть? Если удалось подхватить - добавлять, если нет - то нафиг? Сообщать в prompt, что повторите позднее? (ради такого, мне кажется, нет особого смысла создавать отдельную таблицу ждущих в очереди для обновления названия).

**Comment by alextewpin** [comment]
>Ведь явно не в избранное должно идти, пользователю может оно в избранном и не нужно.
Именно туда. Добавлять доску в общий список, чтобы просмотреть один раз это нечастый сценарий, обычно люди используют одни и те же доски. Кроме того, тогда пользователь не увидит мгновенной обратной связи и может не понять, что вообще что-то добавилось. Придется придумывать еще костыли в виде уведомления или скролла.

Посмотрим на фидбэк, если нужно, то поменяем. 

Пока у доски не подхвачено описание, вторая строка не показывается.

**Comment by alextewpin** [comment]
Писал с мобилы, зафачил цитату (

**Comment by 8ofproject** [comment]
Ок. В этом есть смысл.

**Comment by alextewpin** [comment]
Предложение не совсем корректно, конечно. В публичной версии часть разделов вообще не будет показываться ни при каких условиях, но такая сортировка может быть в девелоперской версии.

**Comment by 8ofproject** [comment]
Готово в eecf8901f9531eb8a96776283b7e109f18ca0d44 за исключением сортировки в девелоперской версии (пока нет времени с этим заморачиваться - будет общий список для всех).
Добавил только те разделы, которые не вызывали проблем при ревью.
