### ISSUE TITLE
поддержка капчи cloudflare для работы с зашквареных IP

### ISSUE THREAD

**Issue by artemy** [8ofproject/2ch-Browser-iOS#180]

**Comment by 8ofproject** [comment]
Подробности бы.

**Comment by artemy** [comment]
Если открыть двач с "неблагонадежного" IP, cloudflare подсовывает свою страницу, на которой нужно ввести капчу.
2ch browser такого поворота не понимает и просто отказывается загружать контент
![05 12 15 20 49 02](https://cloud.githubusercontent.com/assets/132329/11609894/1935a55a-9b93-11e5-8eea-5e52e23f610e.png)
![05 12 15 20 50 29](https://cloud.githubusercontent.com/assets/132329/11609895/1957d094-9b93-11e5-9ac9-5b75a6d4bbca.png)

**Comment by 8ofproject** [comment]
Это какая версия себя так ведёт?

**Comment by artemy** [comment]
Вот 1.4.0 из аппстора

**Comment by 8ofproject** [comment]
Вот как, просто обычно он пытается пеоказать чуть другое окно (с клаудой но без капчи) - это ловится и нормально обрабатывается, а вот такое впервые вижу.
Ты можешь дать адрес страницы клауды с капчей?

**Comment by artemy** [comment]
А как это сделать? Я не могу клаудовский урл в браузере перехватить, оно все на двач редиректит. 
Это можно воспроизвести, если зайти через tunnelbear из Нидерландов. Тут со всех IP клаудфлейр на дваче капчу просит

**Comment by 8ofproject** [comment]
Это уже что-то. Расскажу как будут новости.

**Comment by egv** [comment]
из Венгрии такая же фигня кстати

**Comment by 8ofproject** [comment]
Исправлено 03b97bac265240b0a2f5e3efcf0935a2c3631d9e
Выйдет в свет со следующим обновлением.
