### ISSUE TITLE
Форматирование соглашения

### ISSUE THREAD

**Issue by alextewpin** [8ofproject/2ch-Browser-iOS#19]
Нужно добавить инсеты uiTextView в 16 пт справа и слева и в 8 пт сверху и снизу.

**Comment by 8ofproject** [comment]
Сделано в 7cac95727c28f5af45cf3b96d39317ae8741b2ba
Как-то слишком много по бокам вышло, если сравнивать с верхним.

**Comment by alextewpin** [comment]
Столько предлагает интерфейс билдер. Я гляну и поправлю, если что.

**Comment by alextewpin** [comment]
Посмотрел, все там хорошо.
