### ISSUE TITLE
Добавить возможность делиться ссылками на изображения из галереи

### ISSUE THREAD

**Issue by amayatsky** [8ofproject/2ch-Browser-iOS#190]
Кнопка Copy в MWPhotoBrowser к сожалению копирует не текстовую ссылку, а видимо само изображение в буфер.
Вставить его ни в WhatsApp, ни в Skype не получается.
Можно наверное ее (библиотеку) форкнуть или extension какой сделать чтобы поправить ее поведение?
Могу попробовать сам, но я плохо разбираюсь в ObjC.

**Comment by 8ofproject** [comment]
Для исправления цвета Share кнопки в этом фреймворке пришлось его форкнуть.
Теперь есть возможность и эту задачу решить.

**Comment by amayatsky** [comment]
Почему-то мне кажется что для таких целей reflection бы мог сработать? :)

**Comment by 8ofproject** [comment]
@amayatsky расскажи про reflection

**Comment by amayatsky** [comment]
Я не знаток этого дела в ObjC, но можно же в рантайме поменять метод либы который иконку отдает или переменную где лежит иконка и т.д.
Типа http://nshipster.com/method-swizzling/
Или http://stackoverflow.com/a/25538951/3792318
Тоже самое наверное возможно сделать и для метода который отрабатывает при клике по Share.
Сырцы от либы есть, тыкаться вслепую не надо.

**Comment by 8ofproject** [comment]
@amayatsky Там тогда нужно весь метод переписывать, потому что конкретно к такому типу кнопки .tintColor нормально применяется только в момент создания. Поэтому просто засвиззлить и сменить tintColor после не выйдет.
Кажется что перспектива добавить кнопку в форк выглядит лучше, чем свиззлинг метода и потом сверка версий от разработчика с моей версией при каждом обновлении (я просто забуду об этом через неделю 😆 .
А так просто можно забирать обновления из оригинального репозитория.

**Comment by amayatsky** [comment]
Мне почему-то показалось что та либа сто лет как мертва.
Поэтому я тогда ещё думал что поддержка форка с одной стороны усилий не
потребует, а с другой, мало ли какие проблемы принесут новые версии iOS,
самому форк чинить придётся :)

2 Сен 2016 г. 5:22 пользователь "Andrey Konstantinov" <
notifications@github.com> написал:

**Comment by amayatsky** [comment]
![image](https://cloud.githubusercontent.com/assets/15123185/18199387/369717ba-712a-11e6-8b95-97daa23133cb.png)
Ну да, автор довольно долго считал что трогать ничего в либе не нужно, но она жива, беру свои слова назад. Видимо общение с андроидом меня приучило что SDK и любые либы в состоянии вечной беты, ни дня без апдейта.

**Comment by 8ofproject** [comment]
@amayatsky Принял решение не делать эту задачу и вот почему:
К чему отправка ссылки, если можно сразу отправить файл?
Зачем заставлять принимающую сторону переходить по этой ссылке в браузере и смотреть там эту картинку? UX страдает.
Если отправлять файл, то его сразу можно удобно посмотреть средствами мессенджера, в который отправлен файл.
Ссылка ещё и устареть может, файл вовсе станет недоступен.
Все мессенджеры, кроме скайпа поддерживают копирование файла сразу. В скайп можно его вставить через сохранение файла -> отправка файла в скайпе.
