### ISSUE TITLE
Смена домена

### ISSUE THREAD

**Issue by RogerPaladin** [8ofproject/2ch-Browser-iOS#199]
Необходимо реализовать смену домена в настройках приложения.

**Comment by 8ofproject** [comment]
@RogerPaladin какие есть варианты?

**Comment by RogerPaladin** [comment]
2ch.hk 
2ch.pm
2ch.re
2ch.tf
2ch.yt
2-ch.so
И напрямую по ip

**Comment by 8ofproject** [comment]
@RogerPaladin какую проблему мы решаем таким образом?

**Comment by RogerPaladin** [comment]
В данный момент 2ch.hk (104.20.86.116) не работает/не пингуется, в отличии от 2ch.pm (104.27.197.87). Владельцы пасскодов в данный момент используют 2ch.pm

**Comment by 8ofproject** [comment]
@RogerPaladin спасибо за информацию. Как раз искал работающий домен.

**Comment by 8ofproject** [comment]
Не работают:
+ 2ch.re
+ 2ch.yt
+ 2-ch.so
нет сертификата:
+ 2ch.tf

Будут три:
+ 2ch.hk 
+ 2ch.pm
+ 2channel.hk
