### ISSUE TITLE
На предпросмотровые и большие картинки сервер выдаёт ошибку 403

### ISSUE THREAD

**Issue by 8ofproject** [8ofproject/2ch-Browser-iOS#20]

**Comment by 8ofproject** [comment]
Ошибку 403 можно выловить, если назначать картинки (например в **DVBThreadTableViewCell.m**) не с помощью обычного **sd_setImageWithURL**, а с помощью **completion**.
Ошибка, похоже, связана с CloudFlare. Появляется регулярно при нахождении в одних и тех же сетях. В других сетях всё нормально.
При этом весь текст отображается и старые изображения, загруженные ранее, отображаются заранее.
Не путать с кешем устройства! Речь идёт об изображениях, загруженных на сервер двача до **19 марта** - они показываются нормально везде.

**Comment by 8ofproject** [comment]
Предпринятые попытки обхода/ углубления в проблему:
+ Показать UIWebView со ссылкой на тред, где загружено изображение - **нет ошибки/отображается нормально**
+ Показать UIWebView со ссылкой на само изображение - **нет ошибки/отображается нормально**
+ Проделать всё вышесказанное через браузер Safari - **нет ошибки/отображается нормально**
+ Встроить картинку в *.html-файл, загрузить его ан другой домен и обратиться к файлу (это проверка) - **нет ошибки/отображается нормально**

**Comment by 8ofproject** [comment]
Хотя сами CloudFlare отрицают свою причастность https://support.cloudflare.com/hc/en-us/articles/200169226-Why-am-I-getting-a-403-error-

В тех сетях, где не работают картинки в текущем браузере не работают картинки и в Табуле и в 2ch browser android, то есть проблема новая и раньше её не было.

У меня пока кончились идеи. Может у тебя есть? @alextewpin

**Comment by 8ofproject** [comment]
Появилась идея проверить работу через другие домены (pm, re). Пока не могу проверить потому что всё работает.

**Comment by alextewpin** [comment]
Возможно, рандомные флуктуации в работе двача или КФ. Обычно на картинках нет защиты от ддоса, но пару раз Абу ее вешал на некоторое время и все ломалось. Вебвью в таких случая работает, т.к. КФ проверяет агента с помощью JS. Возможно, что это повторяется, но доступ ограничили не ко всем картинам. Имеет смысл написать Абу в ВК: http://vk.com/abunyasha

**Comment by 8ofproject** [comment]
Уже написал.
Он мне выдал доступ к конфе разработчиков.
Там сказали что это КФ и порекомендовали проверить ответ сервера (ну я и проверил - обычная 403 ошибка, то есть это не ответ API, сообщающий об ошибке, а обычная ошибка Forbidden 403, которую не могу заскриншотить.

**Comment by 8ofproject** [comment]
Проблема исчезла. Больше не могу её воспроизвести.
