### ISSUE TITLE
добавить апкапчу

### ISSUE THREAD

**Issue by wildflypower** [8ofproject/2ch-Browser-iOS#200]
Ключи даст обезьян. 
Пример использования или в вортексовском клиенте или еще где

**Comment by wildflypower** [comment]
https://github.com/wildflypower/2ch-Browser/commit/6f4f93f638004d8c6923f6342a022e0e2e3b9859

Вот коммит с добавлением

**Comment by 8ofproject** [comment]
@wildflypower есть доки по ней? Описание от абу?

**Comment by wildflypower** [comment]
Вортексовский клиент посмотри. 
Суть в том что мобильный клиент отправляет сообщение используя  не введенный клиентом код капчи, который отправляется при добавлении поста. А отправляет сгенереный по алгоритму самим приложением. 
Описание есть в разделе Абу. Ну и текстовик в репе есть с кодами и описанием

**Comment by wildflypower** [comment]
1) https://2ch.hk/api/captcha/app/id/C2hBv0LcE81VOax1WP6Ap6n07JMnhkXx
Получение идентификатора для подписи сообщения.
2) Постинг:
captcha_type = app
app_response_id = идентификатор полученный от запроса к капче на шаге 1
app_response = sha256(app_response_id + "|" + приватный ключ)

Captcha: https://2ch.hk/api/captcha/
Переменная result отвечает за результат выполнения запроса и может принимать следующие значения:
3 - Капча не требуется. Например, в случае если на доске она отключена.
2 - Капча не требуется, поскольку активен VIP аккаунт.
1 - Запрос удовлетворён успешно.
0 - При выполнении запроса возникла ошибка. Код ошибки находится в переменной error, описание ошибки в переменной description. В данный момент спецификация кодов ошибок находится в разработке и скорее всего будет изменена.
