### ISSUE TITLE
Воплотить новый вид (и функционал) окна со списком досок

### ISSUE THREAD

**Issue by 8ofproject** [8ofproject/2ch-Browser-iOS#21]

**Comment by 8ofproject** [comment]
1. При загрузке пользователь видит все, что там было в прошлый раз. Обновления подтягиваются асинхронно, изменяются только те секции таблицы, которые нужно.
2. Доски добавляются сразу в избранное, при свайпе налево появляется кнопка удаления. Если секция избранного пуста, то она не показывается.
3. Добавление доски никогда не вызывает ошибку. Если такой нет, то она просто не загрузится на переходе.
4. Доска добавляется мгновенно, ее имя запрашивается асинхронно.
5. Поиск не виден сразу, он прячется за навбаром.
6. Поиск ищет по заголовкам и описаниям досок.

Цвет плюса: 255, 139, 16. Размеры и цвета всех других элементов стандартные.

XX. Нужно убрать настройки и куда-то это всё перенести

**Comment by 8ofproject** [comment]
@alextewpin  приглашаю тебя к обсуждению, дружище:

Сейчас задался вопросом насчёт пункта - *Если секция избранного пуста, то она не показывается.*

А что если мы будем её показывать всегда?

Плюсы, которые вижу:
+ Мы сообщаем пользователю о том, что у нас появилась такая функция, 
+ Задаваясь вопросом как заполнить секцию своими досками - анон поймёт зачем нужна кнопка ПЛЮС
+ анон - человек постоянный и ходит в одни и те же места - он сразу и заполнит, мало у кого эта секция будет пустой

Минусы:
+ Заголовок секции слипается со следующей "тематика"

А вот если мы не сделаем секцию видимой сразу - то многие могут и не заметить. Я тебе уже рассказывал что куча людей жаловались и спрашивали как попасть в Б, хотя это можно было сделать через ПЛЮС с самого первого дня. (Плюс, кстати, там же находился).

Тоже самое предлагаю сделать с полем Поиск. По тем же причинам.

Что скажешь?

**Comment by alextewpin** [comment]
Да, думаю, что стоит сделать так. Проще всего по умолчанию добавить пару досок в избранное. А пока секция пустая, нужно показывать там нетапабельную ячейку с текстом вида «У вас тут пусто.

Поиск под навбаром по-моему совершенно обычный паттерн и используется даже в стандартных приложениях — посмотри почту или сообщения. Не вижу смысла делать иначе.

На добавлении в избранное нужно текст поменять на алерте:
Заголовок: «Добавить в избранное» (это смысл этого в окна)
Пояснение: «Введите код доски, чтобы добавить ее в избранное»

**Comment by 8ofproject** [comment]
Из всего списка осталось сделать только поле поиска.
