### ISSUE TITLE
Продумать поведение и вид страниц ошибок

### ISSUE THREAD

**Issue by alextewpin** [8ofproject/2ch-Browser-iOS#22]
Нет интернета
404
403
200 + битый JSON или другой невалидный ответ

**Comment by 8ofproject** [comment]
Пока могу сказать что приложение не падает ни при одном из этих случаев. А затем:

+ 404 - ничего не выдаёт
+ 403 - ничего не выдаёт
+ 200 + невалидный - фильтрует ответ, отбрасывает ошибки, в худшем случае (если ошибки начались где-то и не закончились до самого конца) - обрывает обработку и выводит часть без ошибо.

**Comment by 8ofproject** [comment]
Предлагаю при 404 и 403 ошибках если это открытие треда выдавать фон с надписью вроде Ресурс недоступен.

**Comment by alextewpin** [comment]
Еще таймаут. Кстати, сколько он?

**Comment by 8ofproject** [comment]
60 секунд
