### ISSUE TITLE
Вырезать переносы строк в начале и конце поста

### ISSUE THREAD

**Issue by alextewpin** [8ofproject/2ch-Browser-iOS#23]
Часто возникают, особенно в конце поста. На вебе практически незаметно, а в приложении выглядит стремно.

**Comment by 8ofproject** [comment]
Переносы уже вырезаны. Пока вижу что проблема присутствует только в некоторых ОП-постах. В обычных постах такого нет.

**Comment by 8ofproject** [comment]
Переносы в конце и в начале аж дважды вырезаются - в старом коде раз и второй в новом коде когда расставляем разметку. Надо найти тред с проблемой ивывести через **NSLog** содержание первого комментария.

**Comment by 8ofproject** [comment]
В iOS 8.3 проблемы нет. Пробелма присутствует в iOS 7 - скорее всего ошибки изменения ячеек. Почему именно в ОП-постах ума не приложу. Так как iOS 7 поддерживаем "постольку-поскольку" и "лучше так чем никак" - то закрываю issue. Пока основные моменты будем доводить до ума уже выйдет iOS 9 и это всё станет не важно. :trollface:
