### ISSUE TITLE
Изучить соответствие/ не соответствие размера шрифта в приложении размеру шрифта в системных приложениях

### ISSUE THREAD

**Issue by 8ofproject** [8ofproject/2ch-Browser-iOS#87]

**Comment by 8ofproject** [comment]
Всё-таки размер нормальный. Пусть привыкают.

**Comment by euf** [comment]
Да нет же, ненормальный. 
Никак невозможно привыкнуть. 
Столько людей уже просили уменьшить!

**Comment by 8ofproject** [comment]
5 человек из нескольких тысяч? Это просто смешно.

**Comment by 8ofproject** [comment]
P.S. @euf Сам я это делать не стану - если хочешь - можешь заняться.

**Comment by egv** [comment]
@8ofproject а у тебя шрифты берутся по системной настройке или нет? Скорее всего просят уменьшить те, кто выкручивают на минимум размер системного шрифта и потом у них вытекают глаза

**Comment by 8ofproject** [comment]
@egv Да - из системной настройки динамического шрифта.
Судя по всему настройка у большинства стоит в середине (это ожидаемо, пользователи iOS не особо по настройкам гуляют). На мой взгляд при таком размере и вправду текст великоват - но я как раз один из тех кто всегда его влево выкручивает - поэтому я выкручиваю и становится идеально.

![screenshot 2015-05-11 02 18 50](https://cloud.githubusercontent.com/assets/6408861/7556643/28a931fe-f784-11e4-8a4e-a52f3efbc6a7.png)
